package app.tabit.tracker.core.theme

import androidx.compose.ui.graphics.Color

val md_primary_light = Color(0xFF006B5E)
val md_on_primary_light = Color(0xFFFFFFFF)
val md_primary_container_light = Color(0xFF7AF8DE)
val md_on_primary_container_light = Color(0xFF00201B)
val md_secondary_light = Color(0xFF4A635C)
val md_on_secondary_light = Color(0xFFFFFFFF)
val md_tertiary_light = Color(0xFF436259)
val md_on_tertiary_light = Color(0xFFFFFFFF)
val md_error_light = Color(0xFFBA1A1A)
val md_on_error_light = Color(0xFFFFFFFF)
val md_background_light = Color(0xFFF8FAF8)
val md_on_background_light = Color(0xFF191C1B)
val md_surface_light = Color(0xFFF8FAF8)
val md_on_surface_light = Color(0xFF191C1B)

val md_primary_dark = Color(0xFF5CDBC2)
val md_on_primary_dark = Color(0xFF003730)
val md_primary_container_dark = Color(0xFF005045)
val md_on_primary_container_dark = Color(0xFF7AF8DE)
val md_secondary_dark = Color(0xFFB0CFC6)
val md_on_secondary_dark = Color(0xFF1C352E)
val md_tertiary_dark = Color(0xFFA3D0C3)
val md_on_tertiary_dark = Color(0xFF0E2D25)
val md_error_dark = Color(0xFFFFB4AB)
val md_on_error_dark = Color(0xFF690005)
val md_background_dark = Color(0xFF191C1B)
val md_on_background_dark = Color(0xFFE0E3E0)
val md_surface_dark = Color(0xFF191C1B)
val md_on_surface_dark = Color(0xFFE0E3E0)
